[tool.poetry]
name = "pureskillgg-csgo-dsdk"
version = "0.6.0"
description = "Python Data Science Development Kit for CS:GO."
authors = ["PureSkill.gg <contact@pureskill.gg>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/pureskillgg/csgo-dsdk"
repository = "https://github.com/pureskillgg/csgo-dsdk"
include = ['poetry.lock']

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.2"
pureskillgg-dsdk = ">=0.14.0"
structlog = "^21.1.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
bump2version = "^1.0.0"
pylint = "^2.4.0"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-runner = "^6.0.0"
pytest-watch = "^4.2.0"
twine = "^3.0.0"
wheel = "^0.34.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
